on:
  push:
    branches:
      - master

name: Deploy Aplication

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Chrome Driver'
        uses: nanasess/setup-chromedriver@master
      - name: 'Configure Chrome Driver'
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: 'Setup Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'
      
      - name: 'Setup phantomjs'
        run: sudo apt install phantomjs -y

  build:
    name: Compile and migrate
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Compile sass'
        run: npm run compile-sass

  deploy:
    needs: build
    name: Ansible deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible requests
      - name: set ansible config secrets
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          SSH_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > .ansible-vault-password
          mkdir .ssh
          echo "$SSH_KEY" > .ssh/id_aws
          chmod 600 .ssh/id_aws
      - name: run exporters playbook
        env:
          DO_API_KEY: ${{ secrets.DO_API_KEY }}d1
        run: |
          ansible-playbook -i inventory playbook.yml
  
