name: Deploy Aplication

on: 
  repository_dispatch:
    types: [my-event]
    
  release:
    types: 
      - created

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Chrome Driver'
        uses: nanasess/setup-chromedriver@master
      - name: 'Configure Chrome Driver'
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: 'Setup Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'
      
      - name: 'Setup phantomjs'
        run: sudo apt install phantomjs -y

  build:
    name: Compile and migrate
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Compile sass'
        run: npm run compile-sass

  deploy:
    needs: build
    name: Ansible deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible requests
      
      - name: Artifact restore
        uses: actions/download-artifact@v1
        with:
          name: artifacts
          path: artifacts

      - name: Setup AWS Cli
        uses: chrislennon/action-aws-cli@v1.1
      
      - name: Download private key
        run: |
          aws s3 cp s3://ci-gorilla-test-habib/${{ secrets.KEY_NAME }}.pem ${{ secrets.KEY_NAME }}.pem
          chmod 400 artifacts/${{ secrets.KEY_NAME }}.pem

      - name: run exporters playbook
        run: |
          ip=$(<artifacts/public_ip)
          ansible-playbook -i playbook.yml --host $ip --user ubuntu --key ${{ secrets.KEY_NAME }}.pem
  
